"""
frontend/pages/4_Quiz.py – AI Quiz & Exam Simulator.
"""
import streamlit as st, time, sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
from frontend.utils.api_client import require_auth, post
from backend.db.mongodb import get_sync_db
from datetime import datetime

st.set_page_config(page_title="Quiz – EduAI", page_icon="❓", layout="wide")
user = require_auth()
st.title("❓ AI Quiz & Exam Simulator")
st.caption("Adaptive MCQs generated by Llama 3 • Timed exam mode • Detailed feedback")

# ── State init ─────────────────────────────────────────────
for key, default in [
    ("quiz_questions", []), ("quiz_answers", {}), ("quiz_submitted", False),
    ("quiz_start_time", None), ("quiz_topic", ""), ("quiz_active", False),
]:
    if key not in st.session_state:
        st.session_state[key] = default

# ── Setup form ─────────────────────────────────────────────
if not st.session_state.quiz_active:
    st.subheader("⚙️ Configure Your Quiz")
    with st.form("quiz_setup"):
        c1, c2, c3 = st.columns(3)
        with c1:
            topic = st.text_input("Topic *", placeholder="e.g., BJT Amplifiers")
            subject = st.text_input("Subject *", placeholder="e.g., Analog Electronics")
        with c2:
            branch = st.selectbox("Branch", ["ECE","CS","ME","CE","EE","IT"],
                                  index=["ECE","CS","ME","CE","EE","IT"].index(
                                      user.get("branch","ECE")) if user.get("branch","ECE") in
                                  ["ECE","CS","ME","CE","EE","IT"] else 0)
            year = st.selectbox("Year", ["1st year","2nd year","3rd year","4th year"], index=2)
        with c3:
            num_q = st.slider("Number of questions", 5, 20, 10)
            timed = st.checkbox("⏱️ Timed mode (2 min/question)", value=True)
        start = st.form_submit_button("🚀 Generate Quiz", type="primary", use_container_width=True)

    if start:
        if not topic or not subject:
            st.error("Topic and Subject are required")
        else:
            with st.spinner("🤖 Generating questions..."):
                result = post("/nlp/quiz", {
                    "topic": topic, "subject": subject,
                    "branch": branch, "year": year, "num_questions": num_q
                })
            if result["ok"]:
                st.session_state.quiz_questions = result["data"]["questions"]
                st.session_state.quiz_answers = {}
                st.session_state.quiz_submitted = False
                st.session_state.quiz_start_time = time.time()
                st.session_state.quiz_topic = topic
                st.session_state.quiz_timed = timed
                st.session_state.quiz_time_limit = num_q * 120  # 2 min per question
                st.session_state.quiz_active = True
                st.rerun()
            else:
                st.error(f"❌ {result['error']}")

# ── Active Quiz ────────────────────────────────────────────
elif st.session_state.quiz_active and not st.session_state.quiz_submitted:
    questions = st.session_state.quiz_questions

    # Timer
    if st.session_state.get("quiz_timed"):
        elapsed = time.time() - st.session_state.quiz_start_time
        remaining = max(0, st.session_state.quiz_time_limit - elapsed)
        mins, secs = divmod(int(remaining), 60)
        timer_color = "red" if remaining < 60 else "orange" if remaining < 300 else "green"
        st.markdown(
            f'<div style="text-align:right;font-size:1.3rem;color:{timer_color};font-weight:700">'
            f'⏱️ {mins:02d}:{secs:02d} remaining</div>',
            unsafe_allow_html=True,
        )
        if remaining == 0:
            st.session_state.quiz_submitted = True
            st.rerun()

    # Progress
    answered = len(st.session_state.quiz_answers)
    st.progress(answered / len(questions), text=f"Answered {answered}/{len(questions)}")

    # Questions
    for i, q in enumerate(questions):
        with st.container():
            st.markdown(f"**Q{i+1}. {q.get('question', '')}**")
            opts = q.get("options", {})
            opt_list = [f"{k}) {v}" for k, v in opts.items()]
            prev = st.session_state.quiz_answers.get(i)
            prev_idx = None
            if prev:
                for idx, opt in enumerate(opt_list):
                    if opt.startswith(prev):
                        prev_idx = idx
                        break
            choice = st.radio("", opt_list, index=prev_idx, key=f"q_{i}", label_visibility="collapsed")
            if choice:
                st.session_state.quiz_answers[i] = choice[0]  # Store letter A/B/C/D
            st.divider()

    c1, c2 = st.columns([3, 1])
    with c2:
        if st.button("📤 Submit Quiz", type="primary", use_container_width=True):
            st.session_state.quiz_submitted = True
            st.rerun()
    with c1:
        if st.button("🗑️ Abandon Quiz", type="secondary"):
            st.session_state.quiz_active = False
            st.rerun()

# ── Results ────────────────────────────────────────────────
elif st.session_state.quiz_submitted:
    questions = st.session_state.quiz_questions
    answers = st.session_state.quiz_answers
    elapsed = int(time.time() - st.session_state.quiz_start_time)

    correct = sum(1 for i, q in enumerate(questions) if answers.get(i) == q.get("answer"))
    score_pct = round(correct / len(questions) * 100, 1)
    grade = "A+" if score_pct >= 90 else "A" if score_pct >= 80 else "B" if score_pct >= 70 else "C" if score_pct >= 60 else "F"

    # Score card
    st.subheader("📊 Quiz Results")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("Score", f"{score_pct}%")
    m2.metric("Correct", f"{correct}/{len(questions)}")
    m3.metric("Grade", grade)
    m4.metric("Time Taken", f"{elapsed//60}m {elapsed%60}s")

    color = "#22c55e" if score_pct >= 70 else "#f59e0b" if score_pct >= 50 else "#ef4444"
    st.markdown(
        f'<div style="background:{color}22;border-left:4px solid {color};padding:1rem;border-radius:8px;margin:1rem 0">'
        f'{"🎉 Excellent work!" if score_pct>=80 else "👍 Good effort!" if score_pct>=60 else "📖 Keep studying — review the explanations below."}</div>',
        unsafe_allow_html=True,
    )

    # Save to MongoDB
    try:
        db = get_sync_db()
        db.quiz_results.insert_one({
            "user_id": str(user.get("_id", "")),
            "email": user.get("email"),
            "topic": st.session_state.quiz_topic,
            "score": score_pct,
            "correct": correct,
            "total": len(questions),
            "time_taken_sec": elapsed,
            "grade": grade,
            "timestamp": datetime.utcnow(),
        })
    except Exception:
        pass

    # Detailed review
    st.subheader("📝 Detailed Review")
    for i, q in enumerate(questions):
        user_ans = answers.get(i, "—")
        correct_ans = q.get("answer", "")
        is_correct = user_ans == correct_ans
        icon = "✅" if is_correct else "❌"
        opts = q.get("options", {})
        with st.expander(f"{icon} Q{i+1}: {q.get('question','')[:80]}..."):
            for letter, text in opts.items():
                color = ""
                if letter == correct_ans:
                    color = "background:#dcfce7;padding:4px 8px;border-radius:4px"
                elif letter == user_ans and not is_correct:
                    color = "background:#fee2e2;padding:4px 8px;border-radius:4px"
                st.markdown(f'<span style="{color}">{letter}) {text}</span>', unsafe_allow_html=True)
            st.markdown(f"**Your answer:** {user_ans} | **Correct:** {correct_ans}")
            if q.get("explanation"):
                st.info(f"💡 {q['explanation']}")

    if st.button("🔄 Take Another Quiz", type="primary"):
        st.session_state.quiz_active = False
        st.session_state.quiz_submitted = False
        st.rerun()
